apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: loki-deployment 
  labels: 
    app: loki 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: loki 
  template: 
    metadata: 
      labels: 
        app: loki 
    spec: 
      securityContext: 
        runAsUser: 0 
      containers: 
      - name: loki 
        image: grafana/loki:latest 
        args: 
        - "--config.file=/loki/local-config.yaml" 
        ports: 
        - name: loki 
          containerPort: 3100 
        volumeMounts: 
        - name: loki-data 
          mountPath: /loki/ 
      volumes: 
      - name: loki-data 
        persistentVolumeClaim: 
          claimName: loki-data-pvc