apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-configmap
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /loki
      replication_factor: 1
      storage:
        s3:
          endpoint: minio-service:9000
          s3forcepathstyle: true
          bucketnames: loki
          access_key_id: minio_access_key
          secret_access_key: minio_secret_key
          insecure: true
      ring:
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h