apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-configmap
  labels:
    app: scdf
data:
  application-kubernetes.yaml: |-
    logging:
      level:
        root: info
        org.springframework: debug
    management:
      defaults:
        metrics:
          export:
            enabled: false
    spring:
      output:
        ansi:
          enabled: NEVER
      cloud:
        deployer:
          kubernetes:
            imagePullPolicy: Always
            imagePullSecret: regcred
        dataflow:
          metrics.dashboard:
            url: 'http://scdf.bluesky.local'
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    imagePullPolicy: Always
                    imagePullSecret: regcred
                    limits:
                      memory: 1024Mi
    maven:
      remote-repositories:
        repo1:
          url: http://nexus-service:8082/repository/maven-public