apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube
        ports:
        - containerPort: 9000
        env:
        - name: SONAR_JDBC_URL
          value: "jdbc:sqlserver://mssql-service;databaseName=sonarqube;encrypt=false"
        - name: SONAR_JDBC_USERNAME
          value: "sa"
        - name: SONAR_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mssql-sa-password
              name: mssql-secret
        - name: STARTUP_SCRIPT
          value: |
            #! /bin/bash
            sysctl -w vm.max_map_count=262144
            echo "done"
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        - name: sonarqube-logs
          mountPath: /opt/sonarqube/logs
        - name: sonarqube-extensions
          mountPath: /opt/sonarqube/extensions
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim: 
          claimName: sonarqube-data-pvc
      - name: sonarqube-logs
        persistentVolumeClaim: 
          claimName: sonarqube-logs-pvc
      - name: sonarqube-extensions
        persistentVolumeClaim: 
          claimName: sonarqube-extensions-pvc