apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      # initContainers:
      # - name: volume-mount-hack
        # image: busybox
        # command: ["sh", "-c", "chmod -R 777 /usr/share/elasticsearch"]
        # volumeMounts:
        # - name: elasticsearch-data
          # mountPath: /usr/share/elasticsearch/data
      containers:
      - name: kibana
        image: kibana:8.6.2
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config
      volumes:
      - name: kibana-config
        persistentVolumeClaim: 
          claimName: kibana-config-pvc