apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-config-pvc
spec:
  volumeName: elasticsearch-config-pv
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-pvc
spec:
  volumeName: elasticsearch-data-pv
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  