apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: prometheus-deployment 
  labels: 
    app: prometheus 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: prometheus 
  template: 
    metadata: 
      labels: 
        app: prometheus 
    spec: 
      securityContext: 
        runAsUser: 0 
      containers: 
      - name: prometheus 
        image: prom/prometheus:latest 
        args: 
        - "--web.enable-lifecycle" 
        ports: 
        - name: prometheus 
          containerPort: 9090 
        volumeMounts: 
        - name: prometheus-data 
          mountPath: /prometheus/ 
      volumes: 
      - name: prometheus-data 
        persistentVolumeClaim: 
          claimName: prometheus-data-pvc