apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      # 어쩔수 없이 사용
      securityContext:
        runAsUser: 0
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args:
        - "--web.enable-lifecycle"
        ports:
        - name: prometheus
          containerPort: 9090
        volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus/
      volumes:
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data-pvc
