apiVersion: v1
kind: PersistentVolume
metadata:
  name: matter-server-data-pv
  labels:
    app: matter-server-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
# work
    path: /mnt/c/data/matter-server-data
# home
#    path: /mnt/f/dev/data/matter-server-data
