apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data-pvc
spec:
  volumeName: matter-server-data-pv
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
