apiVersion: v1
kind: Service
metadata:
  name: smocker-service
spec:
  selector:
    app: smocker
  ports:
  - protocol: TCP
    name: smocker-port-8080
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: smocker-port-8081
    port: 8081
    targetPort: 8081