apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
  - name: elasticsearch-httpport
    port: 9200
    targetPort: 9200
  - name: elasticsearch-transport
    port: 9300
    targetPort: 9300