apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      # initContainers:
      # - name: volume-mount-hack
        # image: busybox
        # command: ["sh", "-c", "chmod -R 777 /usr/share/elasticsearch"]
        # volumeMounts:
        # - name: elasticsearch-data
          # mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        image: elasticsearch:8.6.2
        env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config
          # mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          # subPath : elasticsearch.yml
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim: 
          claimName: elasticsearch-data-pvc
      - name: elasticsearch-config
        persistentVolumeClaim: 
          claimName: elasticsearch-config-pvc
      # - name: elasticsearch-config
        # configMap:
          # name: elasticsearch-configmap
          # items:
          # - key: elasticsearch.yml
            # path: elasticsearch.yml
