apiVersion: v1
kind: Service
metadata:
  name: skipper-service
spec:
  selector:
    app: skipper
  ports:
  - protocol: TCP
    name: skipper-http
    port: 7577
    targetPort: 7577
  - protocol: TCP
    name: skipper-jdwp
    port: 8000
    targetPort: 8000
#  type: LoadBalancer
