apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper-deployment
  labels:
    app: skipper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skipper
  template:
    metadata:
      labels:
        app: skipper
    spec:
      containers:
      - name: skipper
        image: springcloud/spring-cloud-skipper-server:2.11.0-SNAPSHOT
#        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config
            mountPath: /workspace/config
            readOnly: true
#          - name: database
#            mountPath: /etc/secrets/database
#            readOnly: true
        ports:
        - containerPort: 7577
          name: http-skipper
        - containerPort: 8000
          name: jdwp-skipper
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 7577
          initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 7577
          initialDelaySeconds: 1
        startupProbe:
          tcpSocket:
            port: 7577
          failureThreshold: 10
          timeoutSeconds: 2
          initialDelaySeconds: 50
          periodSeconds: 3
        resources:
          requests:
            cpu: 0.5
            memory: 640Mi
        env:
          - name: LANG
            value: en_US.utf8
          - name: LC_ALL
            value: en_US.utf8
          - name: JDK_JAVA_OPTIONS
            value: '-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8'
          - name: SPRING_PROFILES_ACTIVE
            value: 'kubernetes'
          - name: SERVER_PORT
            value: '7577'
          - name: SPRING_CLOUD_CONFIG_ENABLED
            value: 'false'
          - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLE_API
            value: 'false'
          - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
            value: 'false'
#          - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
#            value: /etc/secrets
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                key: postgres-user
                name: postgres-secret
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres-password
                name: postgres-secret
          - name: SPRING_DATASOURCE_URL
            value: 'jdbc:postgresql://postgres-service:5432/spring_skipper'
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: 'org.postgresql.Driver'
          - name: SPRING_DATASOURCE_TEST_ON_BORROW
            value: 'true'
          - name: SPRING_DATASOURCE_VALIDATION_QUERY
            value: 'SELECT 1'
          - name: SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_USE_UNICODE
            value: 'true'
          - name: SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_CHARACTER_ENCODING
            value: 'UTF-8'
#      serviceAccountName: scdf-sa
      volumes:
        - name: config
          configMap:
            name: skipper-configmap
            items:
            - key: 'application-kubernetes.yaml'
              path: 'application-kubernetes.yaml'
#        - name: database
#          secret:
#            secretName: ${DATABASE}