apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluesky-default-ingress
  namespace: default
spec:
  rules:
  - host: elasticsearch.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-service
            port:
              number: 9200
  - host: kibana.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibana-service
            port:
              number: 5601
  - host: loki.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loki-service
            port:
              number: 3100
  - host: mockoon.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mockoon-service
            port:
              number: 3000
  - host: prometheus.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090
  - host: promtail.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: promtail-service
            port:
              number: 3101
  - host: scdf.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scdf-service
            port:
              number: 9393
  - host: skipper.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: skipper-service
            port:
              number: 7577
  - host: smocker.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smocker-service
            port:
              number: 8080
  - host: smocker-ui.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smocker-service
            port:
              number: 8081
  - host: wiremock.bluesky.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wiremock-service
            port:
              number: 8080
