apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-configmap
data:
  promtail.yaml: |
    server:
      # enable_runtime_reload: true
      log_level: info
      http_listen_port: 3101
    
    clients:
    - url: http://loki-service:3100/loki/api/v1/push
    
    positions:
      filename: /run/promtail/positions.yaml
    target_config:
      sync_period: 10s
    scrape_configs:
    # - job_name: system
      # static_configs:
      # - targets:
          # - localhost
        # labels:
          # job: varlogs
          # __path__: /var/log/pods/**/*.log
    - job_name: bluesky-spring-job
      # pipeline_stages:
      # - docker: {}
      kubernetes_sd_configs:
      - role: pod
        selectors:
        - role: pod
          # field: status.phase=Running
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: keep
        regex: spring
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: bluesky-web-gate
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: application
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
