apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: promtail
        image: grafana/promtail
        args:
        - -config.file=/etc/promtail/promtail.yaml
        ports:
        - name: promtail
          containerPort: 3101
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
        - name: promtail-run
          mountPath: /run/promtail
        - name: promtail-containers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: promtail-pods
          mountPath: /var/log/pods
          # readOnly: true
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-configmap
          items:
          - key: promtail.yaml
            path: promtail.yaml
      - name: promtail-run
        hostPath:
          path: /run/promtail
      - name: promtail-containers
        hostPath:
          path: /var/lib/docker/containers
      - name: promtail-pods
        hostPath:
          path: /var/log/pods