apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-config-pv
  labels:
    app: elasticsearch-config-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/c/data/elasticsearch-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv
  labels:
    app: elasticsearch-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/c/data/elasticsearch-data