apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-config-pv
  labels:
    app: kibana-config-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/c/data/kibana-config